# docker-compose.dev.yml (ROOT DIRECTORY)
# Development overrides - use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: "3.8"

services:
  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - DEBUG=influencelytic:*
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  ai-service:
    environment:
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
      - RELOAD=true
    volumes:
      - ./ai_service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Hot reload for development
  hot-reload:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
